project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/01-de_test-focus_pars_tub.qmd
      title: Differential expression analysis of Developmental Hypothalamus datasets from Kim DW et al., 2020 and Romanov et al., 2020 with focus on Pars Tuberalis

format:
  elsevier-html:
    code-fold: true
    comments:
      hypothesis: true
    theme: zephyr
    citations-hover: true
    crossrefs-hover: true
    title-block-style: manuscript
  docx: default
  jats: default
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Developmental Cell
      formatting: preprint
      # model: 3p # Don't set a model with preprint
      cite-style: number

execute:
  freeze: auto
