on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.5
          tinytex: true
          lfs: true

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          lfs: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
